{"name": "test_Find_Bind_Third_User[myfixture3]", "status": "broken", "statusDetails": {"message": "pymysql.err.InternalError: (1105, \"Unknown column 'customer_third_id' in 'where clause'\")", "trace": "self = <utils.pysql.PyMySQL object at 0x00000000054CEC50>\nsql = \"select cust_id from customer_third where customer_third_id='18600000681'\"\n\n    def mysqlget(self, sql):\n    \n        try:\n            cursor = self.conn.cursor()\n>           cursor.execute(sql)\n\nutils\\pysql.py:86: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.cursors.Cursor object at 0x00000000054CE390>\nquery = \"select cust_id from customer_third where customer_third_id='18600000681'\"\nargs = None\n\n    def execute(self, query, args=None):\n        \"\"\"Execute a query\n    \n        :param str query: Query to execute.\n    \n        :param args: parameters used with query. (optional)\n        :type args: tuple, list or dict\n    \n        :return: Number of affected rows\n        :rtype: int\n    \n        If args is a list or tuple, %s can be used as a placeholder in the query.\n        If args is a dict, %(name)s can be used as a placeholder in the query.\n        \"\"\"\n        while self.nextset():\n            pass\n    \n        query = self.mogrify(query, args)\n    \n>       result = self._query(query)\n\nvenv\\lib\\site-packages\\pymysql\\cursors.py:170: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.cursors.Cursor object at 0x00000000054CE390>\nq = \"select cust_id from customer_third where customer_third_id='18600000681'\"\n\n    def _query(self, q):\n        conn = self._get_db()\n        self._last_executed = q\n        self._clear_result()\n>       conn.query(q)\n\nvenv\\lib\\site-packages\\pymysql\\cursors.py:328: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.connections.Connection object at 0x0000000004C3E1D0>\nsql = b\"select cust_id from customer_third where customer_third_id='18600000681'\"\nunbuffered = False\n\n    def query(self, sql, unbuffered=False):\n        # if DEBUG:\n        #     print(\"DEBUG: sending query:\", sql)\n        if isinstance(sql, text_type) and not (JYTHON or IRONPYTHON):\n            if PY2:\n                sql = sql.encode(self.encoding)\n            else:\n                sql = sql.encode(self.encoding, 'surrogateescape')\n>       self._execute_command(COMMAND.COM_QUERY, sql)\n\nvenv\\lib\\site-packages\\pymysql\\connections.py:516: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pymysql.connections.Connection object at 0x0000000004C3E1D0>\ncommand = 3\nsql = b\"select cust_id from customer_third where customer_third_id='18600000681'\"\n\n    def _execute_command(self, command, sql):\n        \"\"\"\n        :raise InterfaceError: If the connection is closed.\n        :raise ValueError: If no username was specified.\n        \"\"\"\n        if not self._sock:\n>           raise err.InterfaceError(\"(0, '')\")\nE           pymysql.err.InterfaceError: (0, '')\n\nvenv\\lib\\site-packages\\pymysql\\connections.py:750: InterfaceError\n\nDuring handling of the above exception, another exception occurred:\n\n    def teardown_module():\n    \n        #先从customer_third表中找到绑定的cust_id\n        sql=\"select cust_id from customer_third where customer_third_id='\"+Find_Bind_Third_User.initparams['cust_third_id']+\"'\"\n    \n>       custid=PyMySQL().mysqlget(sql)\n\ntestcase\\Loginapi\\Find_Bind_Third_User_test.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutils\\pysql.py:90: in mysqlget\n    cursor.execute(sql)\nvenv\\lib\\site-packages\\pymysql\\cursors.py:170: in execute\n    result = self._query(query)\nvenv\\lib\\site-packages\\pymysql\\cursors.py:328: in _query\n    conn.query(q)\nvenv\\lib\\site-packages\\pymysql\\connections.py:517: in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\nvenv\\lib\\site-packages\\pymysql\\connections.py:732: in _read_query_result\n    result.read()\nvenv\\lib\\site-packages\\pymysql\\connections.py:1075: in read\n    first_packet = self.connection._read_packet()\nvenv\\lib\\site-packages\\pymysql\\connections.py:684: in _read_packet\n    packet.check_error()\nvenv\\lib\\site-packages\\pymysql\\protocol.py:220: in check_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b\"\\xffQ\\x04#HY000Unknown column 'customer_third_id' in 'where clause'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack('<h', data[1:3])[0]\n        is_41 = data[3:4] == b\"#\"\n        if is_41:\n            # client protocol 4.1\n            errval = data[9:].decode('utf-8', 'replace')\n        else:\n            errval = data[3:].decode('utf-8', 'replace')\n        errorclass = error_map.get(errno, InternalError)\n>       raise errorclass(errno, errval)\nE       pymysql.err.InternalError: (1105, \"Unknown column 'customer_third_id' in 'where clause'\")\n\nvenv\\lib\\site-packages\\pymysql\\err.py:109: InternalError"}, "parameters": [{"name": "myfixture", "value": "({'cust_third_id': '18600000681', 'appkey': 1103}, ('0', '请求成功'))"}], "start": 1619518824990, "stop": 1619518825188, "uuid": "44c0c0b1-b095-4694-bb89-dc79243f588b", "historyId": "19feef925b0f7d014a7fa175be39a814", "testCaseId": "3e1af3275710136f7cb7e7453f071cc1", "fullName": "testcase.Loginapi.Find_Bind_Third_User_test#test_Find_Bind_Third_User", "labels": [{"name": "tag", "value": "find_bind_third_user"}, {"name": "tag", "value": "flaky(reruns=1, reruns_delay=5)"}, {"name": "parentSuite", "value": "testcase.Loginapi"}, {"name": "suite", "value": "Find_Bind_Third_User_test"}, {"name": "host", "value": "A06P-A90F12DAA"}, {"name": "thread", "value": "7228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.Loginapi.Find_Bind_Third_User_test"}]}