{"uuid": "9c6bb631-b094-4e7f-aa80-04d9d71235ca", "children": ["e4d42630-3eff-4e80-8e50-61b39d123564"], "befores": [{"name": "_Module__pytest_setup_module", "status": "passed", "start": 1619518680458, "stop": 1619518680458}], "afters": [{"name": "_Module__pytest_setup_module::0", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n", "trace": "  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 474, in xunit_setup_module_fixture\n    _call_with_optional_argument(teardown_module, request.module)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\testcase\\Loginapi\\Find_Bind_Third_User_test.py\", line 66, in teardown_module\n    custid=PyMySQL().mysqlget(sql)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\utils\\pysql.py\", line 90, in mysqlget\n    cursor.execute(sql)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 170, in execute\n    result = self._query(query)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 328, in _query\n    conn.query(q)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 517, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 732, in _read_query_result\n    result.read()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 1075, in read\n    first_packet = self.connection._read_packet()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 657, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 707, in _read_bytes\n    CR.CR_SERVER_LOST, \"Lost connection to MySQL server during query\")\n"}, "start": 1619518680545, "stop": 1619518680576}], "start": 1619518680458, "stop": 1619518680576}