{"uuid": "97a175c0-a0e3-46e0-ac1b-78b4bec9f187", "children": ["0bb44e87-fbe4-4d55-b625-a031023b8ab8", "935221b6-bcc9-4245-87eb-7b5968deaebf", "edfd2100-a273-4f3a-8164-912517591183", "35a59c87-defb-4371-b6e6-979b1f859582", "a29df394-0783-4225-8bc5-99d929bfbbeb", "8b341dc5-0683-4706-981d-d9217b1628e8", "ebf9927e-6b29-449f-a040-d5ee8aaa1173", "923d082e-cd58-4ade-89b7-b673263752c4", "638a3426-ca81-4464-96de-f6d95ec9268f"], "befores": [{"name": "_Module__pytest_setup_module", "status": "broken", "statusDetails": {"message": "pymysql.err.InterfaceError: (0, '')\n", "trace": "  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 471, in xunit_setup_module_fixture\n    _call_with_optional_argument(setup_module, request.module)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\testcase\\Loginapi\\third_register_bind_test.py\", line 157, in setup_module\n    PyMySQL().mysqlinsert('customer_verify_sms',insert_data)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\utils\\pysql.py\", line 127, in mysqlinsert\n    self.conn.commit()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 419, in commit\n    self._execute_command(COMMAND.COM_QUERY, \"COMMIT\")\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 750, in _execute_command\n    raise err.InterfaceError(\"(0, '')\")\n"}, "start": 1619432931546, "stop": 1619432931615}, {"name": "_Module__pytest_setup_module", "status": "broken", "statusDetails": {"message": "pymysql.err.InterfaceError: (0, '')\n", "trace": "  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 471, in xunit_setup_module_fixture\n    _call_with_optional_argument(setup_module, request.module)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\testcase\\Loginapi\\third_register_bind_test.py\", line 157, in setup_module\n    PyMySQL().mysqlinsert('customer_verify_sms',insert_data)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\utils\\pysql.py\", line 127, in mysqlinsert\n    self.conn.commit()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 419, in commit\n    self._execute_command(COMMAND.COM_QUERY, \"COMMIT\")\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 750, in _execute_command\n    raise err.InterfaceError(\"(0, '')\")\n"}, "start": 1619432941944, "stop": 1619432942220}, {"name": "_Module__pytest_setup_module", "status": "broken", "statusDetails": {"message": "pymysql.err.InterfaceError: (0, '')\n", "trace": "  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 471, in xunit_setup_module_fixture\n    _call_with_optional_argument(setup_module, request.module)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\testcase\\Loginapi\\third_register_bind_test.py\", line 157, in setup_module\n    PyMySQL().mysqlinsert('customer_verify_sms',insert_data)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\utils\\pysql.py\", line 127, in mysqlinsert\n    self.conn.commit()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 419, in commit\n    self._execute_command(COMMAND.COM_QUERY, \"COMMIT\")\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 750, in _execute_command\n    raise err.InterfaceError(\"(0, '')\")\n"}, "start": 1619432952556, "stop": 1619432952621}, {"name": "_Module__pytest_setup_module", "status": "broken", "statusDetails": {"message": "pymysql.err.InterfaceError: (0, '')\n", "trace": "  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 471, in xunit_setup_module_fixture\n    _call_with_optional_argument(setup_module, request.module)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\testcase\\Loginapi\\third_register_bind_test.py\", line 157, in setup_module\n    PyMySQL().mysqlinsert('customer_verify_sms',insert_data)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\utils\\pysql.py\", line 127, in mysqlinsert\n    self.conn.commit()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 419, in commit\n    self._execute_command(COMMAND.COM_QUERY, \"COMMIT\")\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 750, in _execute_command\n    raise err.InterfaceError(\"(0, '')\")\n"}, "start": 1619432962945, "stop": 1619432963018}, {"name": "_Module__pytest_setup_module", "status": "broken", "statusDetails": {"message": "pymysql.err.InterfaceError: (0, '')\n", "trace": "  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 471, in xunit_setup_module_fixture\n    _call_with_optional_argument(setup_module, request.module)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\testcase\\Loginapi\\third_register_bind_test.py\", line 157, in setup_module\n    PyMySQL().mysqlinsert('customer_verify_sms',insert_data)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\utils\\pysql.py\", line 127, in mysqlinsert\n    self.conn.commit()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 419, in commit\n    self._execute_command(COMMAND.COM_QUERY, \"COMMIT\")\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 750, in _execute_command\n    raise err.InterfaceError(\"(0, '')\")\n"}, "start": 1619432973334, "stop": 1619432973406}], "start": 1619432973334, "stop": 1619432973743}